# #########################################################
# this makefile allows building and cleaning the toggle demo
#
# Copyright (c) 2011 Steve Denson
# MIT Licensed
# #########################################################

# Propeller Demo include
PROPLIB = ../common

CFLAGS = -Os -mno-fcache
CHIP = p2

#
# objects for this program
#

NAME = blink

OBJS = \
blink.o

all: $(NAME).elf

include $(PROPLIB)/common.mk
