/* the library version consists of:
 *     the newlib version number (1.19.0, for us)
 *     then the Propeller revision number
 */

#define VERSION_NUMBER "1.19.0 Parallax version 1"

const char libc_version[] =
"newlib version " VERSION_NUMBER;

const char cvs_id[] = "$Name:  $ $ID: $";

const char libc_copyright[] =
"Copyright (c)2011 Parallax, Inc.\n"
"Newlib is also copyright:\n"
"(1) University of California, Berkeley\n"
"\n"
"Copyright (c) 1990 The Regents of the University of California.\n"
"All rights reserved.\n"
"\n"
"Redistribution and use in source and binary forms are permitted\n"
"provided that the above copyright notice and this paragraph are\n"
"duplicated in all such forms and that any documentation,\n"
"advertising materials, and other materials related to such\n"
"distribution and use acknowledge that the software was developed\n"
"by the University of California, Berkeley.  The name of the\n"
"University may not be used to endorse or promote products derived\n"
"from this software without specific prior written permission.\n"
"THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR\n"
"IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED\n"
"WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.\n"
"\n"
"(2) David M. Gay at AT&T\n"
"\n"
"The author of this software is David M. Gay.\n"
"\n"
"Copyright (c) 1991 by AT&T.\n"
"\n"
"Permission to use, copy, modify, and distribute this software for any\n"
"purpose without fee is hereby granted, provided that this entire notice\n"
"is included in all copies of any software which is or includes a copy\n"
"or modification of this software and in all copies of the supporting\n"
"documentation for such software.\n"
"\n"
"THIS SOFTWARE IS BEING PROVIDED ``AS IS'', WITHOUT ANY EXPRESS OR IMPLIED\n"
"WARRANTY.  IN PARTICULAR, NEITHER THE AUTHOR NOR AT&T MAKES ANY\n"
"REPRESENTATION OR WARRANTY OF ANY KIND CONCERNING THE MERCHANTABILITY\n"
"OF THIS SOFTWARE OR ITS FITNESS FOR ANY PARTICULAR PURPOSE.\n"
"\n"
"(3) Advanced Micro Devices\n"
"\n"
"Copyright 1989, 1990 Advanced Micro Devices, Inc.\n"
"\n"
"This software is the property of Advanced Micro Devices, Inc  (AMD)  which\n"
"specifically  grants the user the right to modify, use and distribute this\n"
"software provided this notice is not removed or altered.  All other rights\n"
"are reserved by AMD.\n"
"\n"
"AMD MAKES NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, WITH REGARD TO THIS\n"
"SOFTWARE.  IN NO EVENT SHALL AMD BE LIABLE FOR INCIDENTAL OR CONSEQUENTIAL\n"
"DAMAGES IN CONNECTION WITH OR ARISING FROM THE FURNISHING, PERFORMANCE, OR\n"
"USE OF THIS SOFTWARE.\n"
"\n"
"(4) C.W. Sandmann\n"
"\n"
"Copyright (C) 1993 C.W. Sandmann\n"
"\n"
"This file may be freely distributed as long as the author's name remains.\n"
"\n"
"(5) Eric Backus\n"
"\n"
"(C) Copyright 1992 Eric Backus\n"
"\n"
"This software may be used freely so long as this copyright notice is\n"
"left intact.  There is no warrantee on this software.\n"
"\n"
"(6) Sun Microsystems\n"
"\n"
"Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved.\n"
"\n"
"Developed at SunPro, a Sun Microsystems, Inc. business.\n"
"Permission to use, copy, modify, and distribute this\n"
"software is freely granted, provided that this notice \n"
"is preserved.\n"
"\n"
"(7) Hewlett Packard\n"
"\n"
"(c) Copyright 1986 HEWLETT-PACKARD COMPANY\n"
"\n"
"To anyone who acknowledges that this file is provided ``AS IS''\n"
"without any express or implied warranty:\n"
"    permission to use, copy, modify, and distribute this file\n"
"for any purpose is hereby granted without fee, provided that\n"
"the above copyright notice and this notice appears in all\n"
"copies, and that the name of Hewlett-Packard Company not be\n"
"used in advertising or publicity pertaining to distribution\n"
"of the software without specific, written prior permission.\n"
"Hewlett-Packard Company makes no representations about the\n"
"suitability of this software for any purpose.\n"
"\n"
"(8) The remaining files in the newlib subdirectory are governed by the\n"
"following copyright.\n"
"\n"
"Copyright (c) 1994 Cygnus Support.\n"
"All rights reserved.\n"
"\n"
"Redistribution and use in source and binary forms are permitted\n"
"provided that the above copyright notice and this paragraph are\n"
"duplicated in all such forms and that any documentation,\n"
"advertising materials, and other materials related to such\n"
"distribution and use acknowledge that the software was developed\n"
"at Cygnus Support, Inc.  Cygnus Support, Inc. may not be used to\n"
"endorse or promote products derived from this software without\n"
"specific prior written permission.\n"
"THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR\n"
"IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED\n"
"WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.\n"
;
