//
// automatically generated by spin2cpp on Mon Oct  8 10:52:49 2012
// ./spin2cpp test.spin 
//

#ifndef testobjSpin_Class_Defined__
#define testobjSpin_Class_Defined__

#include <stdint.h>

class testobjSpin {
public:
  int32_t	Init(void);
private:
};

#endif
