//
// automatically generated by spin2cpp on Mon Oct  8 10:52:49 2012
// ./spin2cpp test.spin 
//

#include <propeller.h>
#include "testobj.h"

#ifdef __GNUC__
#define INLINE__ static inline
#define PostEffect__(X, Y) __extension__({ int32_t tmp__ = (X); (X) = (Y); tmp__; })
#else
#define INLINE__ static
static int32_t tmp__;
#define PostEffect__(X, Y) (tmp__ = (X), (X) = (Y), tmp__)
#endif

int32_t testobjSpin::Init(void)
{
  int32_t result = 0;
  return 0;
}

