//
// automatically generated by spin2cpp on Mon Oct  8 10:52:49 2012
// ./spin2cpp test.spin 
//

#ifndef testSpin_Class_Defined__
#define testSpin_Class_Defined__

#include <stdint.h>
#include "testobj.h"

class testSpin {
public:
  testobjSpin	Myobj;
  int32_t	Main(void);
private:
  int32_t	Foo(int32_t X);
};

#endif
