NAME = xbasic

OBJS = \
xbasic.o \
db_compiler.o \
db_edit.o \
db_expr.o \
db_generate.o \
db_heap.o \
db_image.o \
db_scan.o \
db_statement.o \
db_strings.o \
db_symbols.o \
db_vmdebug.o \
db_vmfcn.o \
db_vmint.o \
buffer.o \
osint_posix.o

#MODEL = xmm
MODEL = xmmc

CFLAGS = -Os -DPROPELLER_GCC

include ../common/common.mk
