NAME = ebasic

OBJS = \
ebasic.o \
db_compiler.o \
db_edit.o \
db_expr.o \
db_generate.o \
db_image.o \
db_scan.o \
db_statement.o \
db_strings.o \
db_symbols.o \
db_vmdebug.o \
db_vmfcn.o \
db_vmint.o \
editbuf.o \
scratchbuf.o \
osint_posix.o

CFLAGS = -Os -DXGSPIC

# basic gnu tools
CC = pic30-gcc
CXX = pic30-g++
LD = pic30-ld
AS = pic30-as
AR = pic30-ar
OBJCOPY = pic30-objcopy
LOADER = pic30-load

$(NAME).elf: $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)

%.o: %.c
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	rm -f *.o *.elf *.a *.cog *.binary
