# #########################################################
# this makefile allows building and cleaning the toggle demo
#
# Copyright (c) 2011 Steve Denson
# MIT Licensed
# #########################################################

# Propeller Demo include
PROPLIB = ../../common

CFLAGS = -Os -mlmm

#
# objects for this program
#

NAME = toggle
OBJS = toggle.o

include $(PROPLIB)/lmmdemo.mk


