#
# objects for this program
#

PROPLIB = ../../common

NAME = fibo
OBJS = fibo.o

# memory model
MODEL = lmm

#
# enable experimental fcache code for this demo
#
#CFLAGS = -Os -mfcache
CFLAGS = -g -Os
#CFLAGS = -g

all: $(NAME).elf

include $(PROPLIB)/common.mk
