# #########################################################
# this makefile allows building and cleaning the toggle demo
#
# Copyright (c) 2011 Steve Denson
# MIT Licensed
# #########################################################

# Propeller Demo include
PROPLIB = ../../libpropeller

CFLAGS = -Os -mlmm

# BSTC program
BSTC=bstc
SPINDIR=.
ECHO=echo

#
# objects for this program
#

NAME = toggle
OBJS = toggle.o toggle_firmware.o $(PROPLIB)/libpropeller.a

include $(PROPLIB)/lmmdemo.mk


