# #########################################################
# This makefile builds the lmm_toggle program
#   
# Copyright (c) 2011 Parallax, Inc.
# All rights MIT licensed
# #########################################################

# Path to shared demo library
PROPLIB = ../../common

#
# objects for this program
#
NAME = toggle
OBJS = toggle.o

# flags to build with
CFLAGS = -Os

# default build target
all: $(NAME).elf

#
# include the fragment that defines most of everything
#
include $(PROPLIB)/lmmdemo.mk
