# #########################################################
# this makefile allows building and cleaning the multi-cog xmm demo
#
# Copyright (c) 2011 Steve Denson
# MIT Licensed
# #########################################################

# Propeller Demo include
PROPLIB = ../common

CFLAGS = -Os

MODEL = xmmc

#
# objects for this program
#

NAME = multi-cog-xmmc

OBJS = \
multi-cog-demo.o

all: $(NAME).elf

include $(PROPLIB)/common.mk
